# File: BackEnd/nixpacks.toml (Percobaan Terakhir)

[phases.setup]
aptPkgs = ["git", "git-lfs"]

[phases.build]
# Menggunakan metode credential helper untuk menyimpan token
cmds = [
    "git config --global credential.helper store",
    "echo \"https://x-access-token:${GITHUB_TOKEN}@github.com\" > ~/.git-credentials",
    "git lfs install",
    "git lfs pull",
    "pip install -r requirements.txt"
]